In [60]:

# Project:- Data Cleaning

# Titanic dataset
# •	Use dataset titanic.dataset.csv.
# •	Remove all the null values.
#  • Remove all the unwanted rows and columns.
#•	Find overall survival rate.
#•	How did survival rate varies by gender, age and passenger id.
#•	Calculate the total of count of male and female.
#•	Cross-validate the female and male data.
#•	Find if there is any correlation between passenger class and survival.

In [34]:
#Using dataset titanic.dataset.csv.
import numpy as np
import pandas as pd
data=pd.read_csv("titanic_dataset.csv")
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [51]:
#Calculating the total of count of male and female.
head_count=data.groupby(["Sex"])["PassengerId"].count()
print("Total Number of Males and Females are:", head_count)

Total Number of Males and Females are: Sex
female    314
male      577
Name: PassengerId, dtype: int64

In [36]:
#Finding all the null values
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [41]:
new_data=data.ffill()  #used forward fill method to handle the null values
new_data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,C85,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,C123,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,C50,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,19.0,1,2,W./C. 6607,23.4500,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,C148,Q

In [43]:
#replaced one null value in Cabin column
new_data.fillna({
    'Cabin':'C85'
})

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,C85,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,C85,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,C123,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,C50,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,19.0,1,2,W./C. 6607,23.4500,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,C148,Q

In [49]:
#Filtering the data again by removing the null values if any
new_data.dropna(inplace=True)
new_data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,C85,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,C123,S
5,6,0,3,"Moran, Mr. James",male,35.0,0,0,330877,8.4583,C123,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,C50,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,19.0,1,2,W./C. 6607,23.4500,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,C148,Q

In [52]:
# Checking if there is any null value present in the data
new_data.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [53]:
#removing all unwanted columns from the data
new_data.drop(['Embarked','Cabin','SibSp','Ticket'],axis=1,inplace=True)
new_data

,PassengerId,Survived,Pclass,Name,Sex,Age,Parch,Fare
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,0,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,0,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,8.0500
5,6,0,3,"Moran, Mr. James",male,35.0,0,8.4583
...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,13.0000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,30.0000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,19.0,2,23.4500
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,30.0000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,7.7500

In [54]:
#Find overall survival rate
Survival_rate=new_data["Survived"].mean()
print("Overall Suvived rate:",Survival_rate)

Overall Suvived rate: 0.3842696629213483

In [55]:
#Cross-validate the female and male data.
Total_count=new_data["PassengerId"].count()
print("Total Paasengers after removing null values: ",Total_count)

head_count=new_data.groupby(["Sex"])["PassengerId"].count()
print("Total Number of Males and Females are:")
head_count

Total Paasengers after removing null values:  890
Total Number of Males and Females are:

Sex
female    314
male      576
Name: PassengerId, dtype: int64

In [58]:
#Find if there is any correlation between passenger class and survival
co_relation=new_data["Pclass"].corr(new_data['Survived'])
print("Correlation between Passenger class and Survivals:",co_relation)

Correlation between Passenger class and Survivals: -0.3379955747032905